-- ============================================================
-- CRK Team Builder - Cookie Roster Seed (GENERATED FILE)
-- Do not edit by hand! Edit cookie_data.json and re-run:
--     node generate_cookie_seed.js
-- Generated: 2026-08-11
-- Source: Cookie Run Kingdom Wiki (Fandom) - List of Cookies
-- ============================================================

TRUNCATE cookies RESTART IDENTITY CASCADE;

INSERT INTO cookies (name, type, position, rarity, image_file, release_date) VALUES
('GingerBrave', 'Charge', 'Front', 'Common', 'gingerbrave.png', '2021-01-21'),
('Strawberry Cookie', 'Defense', 'Front', 'Common', 'strawberry-cookie.png', '2021-01-21'),
('Ninja Cookie', 'Ambush', 'Middle', 'Common', 'ninja-cookie.png', '2021-01-21'),
('Angel Cookie', 'Healing', 'Rear', 'Common', 'angel-cookie.png', '2021-01-21'),
('Muscle Cookie', 'Charge', 'Front', 'Common', 'muscle-cookie.png', '2021-01-21'),
('Wizard Cookie', 'Magic', 'Middle', 'Common', 'wizard-cookie.png', '2021-01-21'),
('Beet Cookie', 'Ranged', 'Rear', 'Common', 'beet-cookie.png', '2021-01-21'),
('Devil Cookie', 'Magic', 'Middle', 'Rare', 'devil-cookie.png', '2021-05-28'),
('Custard Cookie III', 'Healing', 'Rear', 'Rare', 'custard-cookie-iii.png', '2021-01-21'),
('Clover Cookie', 'Support', 'Rear', 'Rare', 'clover-cookie.png', '2021-01-21'),
('Carrot Cookie', 'Support', 'Middle', 'Rare', 'carrot-cookie.png', '2021-01-21'),
('Avocado Cookie', 'Defense', 'Front', 'Rare', 'avocado-cookie.png', '2021-01-21'),
('Pancake Cookie', 'Ambush', 'Rear', 'Rare', 'pancake-cookie.png', '2021-01-21'),
('Onion Cookie', 'Support', 'Middle', 'Rare', 'onion-cookie.png', '2021-01-21'),
('Gumball Cookie', 'Bomber', 'Rear', 'Rare', 'gumball-cookie.png', '2021-01-21'),
('Blackberry Cookie', 'Magic', 'Rear', 'Rare', 'blackberry-cookie.png', '2021-01-21'),
('Adventurer Cookie', 'Ambush', 'Middle', 'Rare', 'adventurer-cookie.png', '2021-01-21'),
('Alchemist Cookie', 'Bomber', 'Middle', 'Rare', 'alchemist-cookie.png', '2021-01-21'),
('Cherry Cookie', 'Bomber', 'Rear', 'Rare', 'cherry-cookie.png', '2021-01-21'),
('Knight Cookie', 'Defense', 'Front', 'Rare', 'knight-cookie.png', '2021-01-21'),
('Princess Cookie', 'Charge', 'Front', 'Rare', 'princess-cookie.png', '2021-01-21'),
('Zoey Cookie', 'Ranged', 'Rear', 'Special', 'zoey-cookie.png', '2026-04-08'),
('Mira Cookie', 'Charge', 'Front', 'Special', 'mira-cookie.png', '2026-04-08'),
('Rumi Cookie', 'Ambush', 'Front', 'Special', 'rumi-cookie.png', '2026-04-08'),
('Marshmallow Bunny Cookie', 'Support', 'Rear', 'Special', 'marshmallow-bunny-cookie.png', '2025-07-02'),
('Cream Ferret Cookie', 'Support', 'Rear', 'Special', 'cream-ferret-cookie.png', '2024-07-17'),
('Icicle Yeti Cookie', 'Healing', 'Front', 'Special', 'icicle-yeti-cookie.png', '2023-11-22'),
('Snapdragon Cookie', 'Support', 'Rear', 'Special', 'snapdragon-cookie.png', '2023-06-08'),
('Jung Kook Cookie', 'BTS', 'Rear', 'Special', 'jung-kook-cookie.png', '2022-10-13'),
('V Cookie', 'BTS', 'Rear', 'Special', 'v-cookie.png', '2022-10-13'),
('Jimin Cookie', 'BTS', 'Rear', 'Special', 'jimin-cookie.png', '2022-10-13'),
('J-hope Cookie', 'BTS', 'Rear', 'Special', 'j-hope-cookie.png', '2022-10-13'),
('SUGA Cookie', 'BTS', 'Rear', 'Special', 'suga-cookie.png', '2022-10-13'),
('Jin Cookie', 'BTS', 'Rear', 'Special', 'jin-cookie.png', '2022-10-13'),
('RM Cookie', 'BTS', 'Rear', 'Special', 'rm-cookie.png', '2022-10-13'),
('Tails Cookie', 'Ambush', 'Middle', 'Special', 'tails-cookie.png', '2021-09-17'),
('Sonic Cookie', 'Ambush', 'Middle', 'Special', 'sonic-cookie.png', '2021-09-17'),
('Litmus Cookie', 'Healing', 'Rear', 'Epic', 'litmus-cookie.png', '2026-06-18'),
('Croissant Cookie', 'Support', 'Rear', 'Epic', 'croissant-cookie.png', '2026-05-21'),
('Ash Salt Cookie', 'Ambush', 'Front', 'Epic', 'ash-salt-cookie.png', '2026-05-07'),
('Pom-Pom Dough Cookie', 'Support', 'Middle', 'Epic', 'pom-pom-dough-cookie.png', '2026-02-11'),
('Mold Dough Cookie', 'Charge', 'Front', 'Epic', 'mold-dough-cookie.png', '2026-01-14'),
('Chess Choco Cookie', 'Bomber', 'Middle', 'Epic', 'chess-choco-cookie.png', '2025-11-19'),
('Salt Cellar Cookie', 'Defense', 'Front', 'Epic', 'salt-cellar-cookie.png', '2025-10-22'),
('Charcoal Cookie', 'Magic', 'Rear', 'Epic', 'charcoal-cookie.png', '2025-09-24'),
('Menthol Cookie', 'Bomber', 'Rear', 'Epic', 'menthol-cookie.png', '2025-08-27'),
('Seltzer Cookie', 'Support', 'Rear', 'Epic', 'seltzer-cookie.png', '2025-08-27'),
('Grapefruit Cookie', 'Charge', 'Front', 'Epic', 'grapefruit-cookie.png', '2025-08-13'),
('Lime Cookie', 'Support', 'Rear', 'Epic', 'lime-cookie.png', '2025-07-30'),
('Manju Cookie', 'Ambush', 'Rear', 'Epic', 'manju-cookie.png', '2025-07-30'),
('Jagae Cookie', 'Support', 'Front', 'Epic', 'jagae-cookie.png', '2025-07-30'),
('Orange Cookie', 'Magic', 'Rear', 'Epic', 'orange-cookie.png', '2025-07-16'),
('Lemon Cookie', 'Ambush', 'Middle', 'Epic', 'lemon-cookie.png', '2025-07-02'),
('Cream Soda Cookie', 'Charge', 'Front', 'Epic', 'cream-soda-cookie.png', '2025-06-25'),
('Sugarfly Cookie', 'Support', 'Rear', 'Epic', 'sugarfly-cookie.png', '2025-06-04'),
('Pavlova Cookie', 'Ranged', 'Rear', 'Epic', 'pavlova-cookie.png', '2025-05-07'),
('Agar Agar Cookie', 'Ambush', 'Middle', 'Epic', 'agar-agar-cookie.png', '2025-04-09'),
('Wedding Cake Cookie', 'Magic', 'Middle', 'Epic', 'wedding-cake-cookie.png', '2025-03-12'),
('Black Forest Cookie', 'Charge', 'Front', 'Epic', 'black-forest-cookie.png', '2025-03-12'),
('Black Sapphire Cookie', 'Support', 'Middle', 'Epic', 'black-sapphire-cookie.png', '2025-02-12'),
('Candy Apple Cookie', 'Bomber', 'Middle', 'Epic', 'candy-apple-cookie.png', '2025-01-15'),
('Okchun Cookie', 'Healing', 'Middle', 'Epic', 'okchun-cookie.png', '2024-12-31'),
('Green Tea Mousse Cookie', 'Defense', 'Front', 'Epic', 'green-tea-mousse-cookie.png', '2024-12-18'),
('Pudding à la Mode Cookie', 'Bomber', 'Rear', 'Epic', 'pudding-a-la-mode-cookie.png', '2024-12-04'),
('Choco Drizzle Cookie', 'Ambush', 'Middle', 'Epic', 'choco-drizzle-cookie.png', '2024-12-04'),
('Red Osmanthus Cookie', 'Ranged', 'Middle', 'Epic', 'red-osmanthus-cookie.png', '2024-11-20'),
('Golden Osmanthus Cookie', 'Bomber', 'Middle', 'Epic', 'golden-osmanthus-cookie.png', '2024-11-20'),
('Smoked Cheese Cookie', 'Magic', 'Rear', 'Epic', 'smoked-cheese-cookie.png', '2024-10-30'),
('Nutmeg Tiger Cookie', 'Support', 'Rear', 'Epic', 'nutmeg-tiger-cookie.png', '2024-10-02'),
('Star Coral Cookie', 'Support', 'Rear', 'Epic', 'star-coral-cookie.png', '2024-08-14'),
('Peach Blossom Cookie', 'Support', 'Middle', 'Epic', 'peach-blossom-cookie.png', '2024-06-28'),
('Cloud Haetae Cookie', 'Defense', 'Front', 'Epic', 'cloud-haetae-cookie.png', '2024-05-22'),
('Street Urchin Cookie', 'Bomber', 'Middle', 'Epic', 'street-urchin-cookie.png', '2024-04-09'),
('Caramel Choux Cookie', 'Support', 'Rear', 'Epic', 'caramel-choux-cookie.png', '2024-03-27'),
('Butter Roll Cookie', 'Charge', 'Front', 'Epic', 'butter-roll-cookie.png', '2024-03-13'),
('Matcha Cookie', 'Magic', 'Middle', 'Epic', 'matcha-cookie.png', '2024-02-28'),
('Mercurial Knight Cookie', 'Charge', 'Front', 'Epic', 'mercurial-knight-cookie.png', '2024-02-07'),
('Silverbell Cookie', 'Support', 'Rear', 'Epic', 'silverbell-cookie.png', '2024-01-19'),
('Rebel Cookie', 'Ambush', 'Front', 'Epic', 'rebel-cookie.png', '2024-01-04'),
('Crème Brûlée Cookie', 'Ranged', 'Rear', 'Epic', 'creme-brulee-cookie.png', '2023-12-13'),
('Linzer Cookie', 'Support', 'Rear', 'Epic', 'linzer-cookie.png', '2023-12-13'),
('Olive Cookie', 'Support', 'Rear', 'Epic', 'olive-cookie.png', '2023-11-03'),
('Mozzarella Cookie', 'Magic', 'Middle', 'Epic', 'mozzarella-cookie.png', '2023-11-03'),
('Fettuccine Cookie', 'Defense', 'Front', 'Epic', 'fettuccine-cookie.png', '2023-10-19'),
('Burnt Cheese Cookie', 'Charge', 'Front', 'Epic', 'burnt-cheese-cookie.png', '2023-09-26'),
('Frilled Jellyfish Cookie', 'Support', 'Middle', 'Epic', 'frilled-jellyfish-cookie.png', '2023-09-08'),
('Peppermint Cookie', 'Support', 'Rear', 'Epic', 'peppermint-cookie.png', '2023-08-09'),
('Black Lemonade Cookie', 'Bomber', 'Middle', 'Epic', 'black-lemonade-cookie.png', '2023-07-21'),
('Rockstar Cookie', 'Healing', 'Middle', 'Epic', 'rockstar-cookie.png', '2023-07-05'),
('Tarte Tatin Cookie', 'Ranged', 'Rear', 'Epic', 'tarte-tatin-cookie.png', '2023-06-08'),
('Royal Margarine Cookie', 'Ambush', 'Middle', 'Epic', 'royal-margarine-cookie.png', '2023-05-18'),
('Kouign-Amann Cookie', 'Defense', 'Front', 'Epic', 'kouign-amann-cookie.png', '2023-04-20'),
('Prune Juice Cookie', 'Bomber', 'Middle', 'Epic', 'prune-juice-cookie.png', '2023-03-30'),
('Space Doughnut', 'Charge', 'Front', 'Epic', 'space-doughnut.png', '2023-03-09'),
('Blueberry Pie Cookie', 'Magic', 'Middle', 'Epic', 'blueberry-pie-cookie.png', '2023-02-14'),
('Milky Way Cookie', 'Charge', 'Front', 'Epic', 'milky-way-cookie.png', '2023-01-19'),
('Prophet Cookie', 'Support', 'Rear', 'Epic', 'prophet-cookie.png', '2023-01-05'),
('Pinecone Cookie', 'Bomber', 'Front', 'Epic', 'pinecone-cookie.png', '2022-12-14'),
('Carol Cookie', 'Healing', 'Rear', 'Epic', 'carol-cookie.png', '2022-11-30'),
('Macaron Cookie', 'Magic', 'Middle', 'Epic', 'macaron-cookie.png', '2022-11-09'),
('Schwarzwälder', 'Charge', 'Front', 'Epic', 'schwarzwalder.png', '2022-10-13'),
('Candy Diver Cookie', 'Support', 'Rear', 'Epic', 'candy-diver-cookie.png', '2022-09-27'),
('Captain Caviar Cookie', 'Bomber', 'Middle', 'Epic', 'captain-caviar-cookie.png', '2022-09-06'),
('Cream Unicorn Cookie', 'Healing', 'Rear', 'Epic', 'cream-unicorn-cookie.png', '2022-07-28'),
('Financier Cookie', 'Defense', 'Front', 'Epic', 'financier-cookie.png', '2022-07-07'),
('Crunchy Chip Cookie', 'Charge', 'Front', 'Epic', 'crunchy-chip-cookie.png', '2022-05-27'),
('Wildberry Cookie', 'Defense', 'Front', 'Epic', 'wildberry-cookie.png', '2022-05-03'),
('Cherry Blossom Cookie', 'Ambush', 'Rear', 'Epic', 'cherry-blossom-cookie.png', '2022-04-18'),
('Caramel Arrow Cookie', 'Ranged', 'Front', 'Epic', 'caramel-arrow-cookie.png', '2022-03-25'),
('Affogato Cookie', 'Bomber', 'Middle', 'Epic', 'affogato-cookie.png', '2022-02-24'),
('Tea Knight Cookie', 'Charge', 'Front', 'Epic', 'tea-knight-cookie.png', '2022-01-19'),
('Eclair Cookie', 'Support', 'Middle', 'Epic', 'eclair-cookie.png', '2022-01-19'),
('Cocoa Cookie', 'Defense', 'Front', 'Epic', 'cocoa-cookie.png', '2021-12-09'),
('Cotton Cookie', 'Support', 'Rear', 'Epic', 'cotton-cookie.png', '2021-11-18'),
('Pumpkin Pie Cookie', 'Magic', 'Middle', 'Epic', 'pumpkin-pie-cookie.png', '2021-10-28'),
('Twizzly Gummy Cookie', 'Ranged', 'Rear', 'Epic', 'twizzly-gummy-cookie.png', '2021-10-08'),
('Mala Sauce Cookie', 'Charge', 'Front', 'Epic', 'mala-sauce-cookie.png', '2021-10-08'),
('Moon Rabbit Cookie', 'Defense', 'Front', 'Epic', 'moon-rabbit-cookie.png', '2021-09-17'),
('Raspberry Cookie', 'Charge', 'Front', 'Epic', 'raspberry-cookie.png', '2021-09-02'),
('Parfait Cookie', 'Support', 'Rear', 'Epic', 'parfait-cookie.png', '2021-08-17'),
('Sorbet Shark Cookie', 'Ambush', 'Middle', 'Epic', 'sorbet-shark-cookie.png', '2021-08-03'),
('Squid Ink Cookie', 'Magic', 'Middle', 'Epic', 'squid-ink-cookie.png', '2021-08-03'),
('Lilac Cookie', 'Support', 'Middle', 'Epic', 'lilac-cookie.png', '2021-07-15'),
('Mango Cookie', 'Magic', 'Middle', 'Epic', 'mango-cookie.png', '2021-06-22'),
('Red Velvet Cookie', 'Charge', 'Front', 'Epic', 'red-velvet-cookie.png', '2021-05-28'),
('Pastry Cookie', 'Ranged', 'Rear', 'Epic', 'pastry-cookie.png', '2021-05-13'),
('Fig Cookie', 'Support', 'Middle', 'Epic', 'fig-cookie.png', '2021-05-13'),
('Strawberry Crepe Cookie', 'Defense', 'Front', 'Epic', 'strawberry-crepe-cookie.png', '2021-04-22'),
('Black Raisin Cookie', 'Ambush', 'Middle', 'Epic', 'black-raisin-cookie.png', '2021-04-08'),
('Almond Cookie', 'Support', 'Middle', 'Epic', 'almond-cookie.png', '2021-03-17'),
('Cream Puff Cookie', 'Support', 'Middle', 'Epic', 'cream-puff-cookie.png', '2021-03-05'),
('Latte Cookie', 'Magic', 'Middle', 'Epic', 'latte-cookie.png', '2021-03-05'),
('Kumiho Cookie', 'Charge', 'Front', 'Epic', 'kumiho-cookie.png', '2021-02-05'),
('Rye Cookie', 'Ranged', 'Rear', 'Epic', 'rye-cookie.png', '2021-01-21'),
('Espresso Cookie', 'Magic', 'Middle', 'Epic', 'espresso-cookie.png', '2021-01-21'),
('Madeleine Cookie', 'Defense', 'Front', 'Epic', 'madeleine-cookie.png', '2021-01-21'),
('Licorice Cookie', 'Magic', 'Middle', 'Epic', 'licorice-cookie.png', '2021-01-21'),
('Poison Mushroom Cookie', 'Bomber', 'Middle', 'Epic', 'poison-mushroom-cookie.png', '2021-01-21'),
('Milk Cookie', 'Defense', 'Front', 'Epic', 'milk-cookie.png', '2021-01-21'),
('Purple Yam Cookie', 'Charge', 'Front', 'Epic', 'purple-yam-cookie.png', '2021-01-21'),
('Pomegranate Cookie', 'Support', 'Middle', 'Epic', 'pomegranate-cookie.png', '2021-01-21'),
('Chili Pepper Cookie', 'Ambush', 'Middle', 'Epic', 'chili-pepper-cookie.png', '2021-01-21'),
('Sparkling Cookie', 'Healing', 'Rear', 'Epic', 'sparkling-cookie.png', '2021-01-21'),
('Dark Choco Cookie', 'Charge', 'Front', 'Epic', 'dark-choco-cookie.png', '2021-01-21'),
('Herb Cookie', 'Healing', 'Rear', 'Epic', 'herb-cookie.png', '2021-01-21'),
('Mint Choco Cookie', 'Support', 'Rear', 'Epic', 'mint-choco-cookie.png', '2021-01-21'),
('Werewolf Cookie', 'Charge', 'Front', 'Epic', 'werewolf-cookie.png', '2021-01-21'),
('Tiger Lily Cookie', 'Ranged', 'Rear', 'Epic', 'tiger-lily-cookie.png', '2021-01-21'),
('Vampire Cookie', 'Ambush', 'Rear', 'Epic', 'vampire-cookie.png', '2021-01-21'),
('Snow Sugar Cookie', 'Magic', 'Middle', 'Epic', 'snow-sugar-cookie.png', '2021-01-21'),
('Povidone-Iodine Cookie', 'Bomber', 'Middle', 'Super Epic', 'povidone-iodine-cookie.png', '2026-06-04'),
('Venom Dough Cookie', 'Bomber', 'Rear', 'Super Epic', 'venom-dough-cookie.png', '2026-01-01'),
('Doughael', 'Healing', 'Middle', 'Super Epic', 'doughael.png', '2025-08-27'),
('Camellia Cookie', 'Charge', 'Front', 'Super Epic', 'camellia-cookie.png', '2024-11-20'),
('Elder Faerie Cookie', 'Defense', 'Front', 'Super Epic', 'elder-faerie-cookie.png', '2024-02-28'),
('Crimson Coral Cookie', 'Defense', 'Front', 'Super Epic', 'crimson-coral-cookie.png', '2023-08-30'),
('Shining Glitter Cookie', 'Magic', 'Middle', 'Super Epic', 'shining-glitter-cookie.png', '2023-07-05'),
('Capsaicin Cookie', 'Charge', 'Front', 'Super Epic', 'capsaicin-cookie.png', '2023-03-30'),
('Stardust Cookie', 'Ambush', 'Middle', 'Super Epic', 'stardust-cookie.png', '2023-03-09'),
('Sherbet Cookie', 'Ranged', 'Middle', 'Super Epic', 'sherbet-cookie.png', '2022-11-30'),
('Oyster Cookie', 'Support', 'Rear', 'Super Epic', 'oyster-cookie.png', '2022-06-14'),
('Clotted Cream Cookie', 'Magic', 'Middle', 'Super Epic', 'clotted-cream-cookie.png', '2022-05-03'),
('Ananas Dragon Cookie', 'Magic', 'Middle', 'Dragon', 'ananas-dragon-cookie.png', '2026-01-01'),
('Pitaya Dragon Cookie', 'Charge', 'Front', 'Dragon', 'pitaya-dragon-cookie.png', '2023-05-18'),
('Timekeeper Cookie', 'Magic', 'Middle', 'Legendary', 'timekeeper-cookie.png', '2026-05-07'),
('Sugar Swan Cookie', 'Healing', 'Rear', 'Legendary', 'sugar-swan-cookie.png', '2026-01-01'),
('Millennial Tree Cookie', 'Healing', 'Front', 'Legendary', 'millennial-tree-cookie.png', '2025-12-17'),
('Fire Spirit Cookie', 'Magic', 'Rear', 'Legendary', 'fire-spirit-cookie.png', '2025-04-09'),
('Wind Archer Cookie', 'Ranged', 'Rear', 'Legendary', 'wind-archer-cookie.png', '2024-09-04'),
('Stormbringer Cookie', 'Charge', 'Front', 'Legendary', 'stormbringer-cookie.png', '2024-04-24'),
('Moonlight Cookie', 'Magic', 'Middle', 'Legendary', 'moonlight-cookie.png', '2023-01-19'),
('Black Pearl Cookie', 'Ambush', 'Middle', 'Legendary', 'black-pearl-cookie.png', '2022-09-06'),
('Frost Queen Cookie', 'Magic', 'Middle', 'Legendary', 'frost-queen-cookie.png', '2021-11-18'),
('Sea Fairy Cookie', 'Bomber', 'Middle', 'Legendary', 'sea-fairy-cookie.png', '2021-06-22'),
('Pure Vanilla Cookie', 'Healing', 'Rear', 'Ancient', 'pure-vanilla-cookie.png', '2021-04-08'),
('Hollyberry Cookie', 'Defense', 'Front', 'Ancient', 'hollyberry-cookie.png', '2021-09-02'),
('Dark Cacao Cookie', 'Charge', 'Front', 'Ancient', 'dark-cacao-cookie.png', '2022-02-24'),
('Golden Cheese Cookie', 'Ranged', 'Middle', 'Ancient', 'golden-cheese-cookie.png', '2023-09-26'),
('White Lily Cookie', 'Bomber', 'Middle', 'Ancient', 'white-lily-cookie.png', '2024-01-19'),
('Dark Cacao Cookie (Dragon Lord)', 'Charge', 'Front', 'Ancient', 'dark-cacao-cookie-dragon-lord.png', '2024-06-28'),
('Golden Cheese Cookie (Immortal)', 'Ranged', 'Middle', 'Ancient', 'golden-cheese-cookie-immortal.png', '2024-10-30'),
('Pure Vanilla Cookie (Compassionate)', 'Healing', 'Rear', 'Ancient', 'pure-vanilla-cookie-compassionate.png', '2025-02-12'),
('Hollyberry Cookie (Aegis)', 'Defense', 'Front', 'Ancient', 'hollyberry-cookie-aegis.png', '2025-06-04'),
('White Lily Cookie (Dawnbringer)', 'Bomber', 'Middle', 'Ancient', 'white-lily-cookie-dawnbringer.png', '2025-10-22'),
('Mystic Flour Cookie', 'Healing', 'Rear', 'Beast', 'mystic-flour-cookie.png', '2024-05-22'),
('Burning Spice Cookie', 'Charge', 'Front', 'Beast', 'burning-spice-cookie.png', '2024-10-02'),
('Shadow Milk Cookie', 'Magic', 'Middle', 'Beast', 'shadow-milk-cookie.png', '2025-01-15'),
('Eternal Sugar Cookie', 'Bomber', 'Middle', 'Beast', 'eternal-sugar-cookie.png', '2025-05-07'),
('Silent Salt Cookie', 'Ambush', 'Front', 'Beast', 'silent-salt-cookie.png', '2025-09-24'),
('Dark Enchantress Cookie', 'Magic', 'Middle', 'Witch', 'dark-enchantress-cookie.png', '2026-01-14');
