-- ============================================================
-- CRK Team Builder - Cookie Roster Seed (GENERATED FILE)
-- Do not edit by hand! Edit cookie_data.json and re-run:
--     node generate_cookie_seed.js
-- Generated: 2026-07-14
-- Source: Cookie Run Kingdom Wiki (Fandom) - List of Cookies
-- ============================================================

TRUNCATE cookies RESTART IDENTITY CASCADE;

INSERT INTO cookies (name, type, position, rarity, image_file) VALUES
('GingerBrave', 'Charge', 'Front', 'Common', 'gingerbrave.png'),
('Strawberry Cookie', 'Defense', 'Front', 'Common', 'strawberry-cookie.png'),
('Ninja Cookie', 'Ambush', 'Middle', 'Common', 'ninja-cookie.png'),
('Angel Cookie', 'Healing', 'Rear', 'Common', 'angel-cookie.png'),
('Muscle Cookie', 'Charge', 'Front', 'Common', 'muscle-cookie.png'),
('Wizard Cookie', 'Magic', 'Middle', 'Common', 'wizard-cookie.png'),
('Beet Cookie', 'Ranged', 'Rear', 'Common', 'beet-cookie.png'),
('Devil Cookie', 'Magic', 'Middle', 'Rare', 'devil-cookie.png'),
('Custard Cookie III', 'Healing', 'Rear', 'Rare', 'custard-cookie-iii.png'),
('Clover Cookie', 'Support', 'Rear', 'Rare', 'clover-cookie.png'),
('Carrot Cookie', 'Support', 'Middle', 'Rare', 'carrot-cookie.png'),
('Avocado Cookie', 'Defense', 'Front', 'Rare', 'avocado-cookie.png'),
('Pancake Cookie', 'Ambush', 'Rear', 'Rare', 'pancake-cookie.png'),
('Onion Cookie', 'Support', 'Middle', 'Rare', 'onion-cookie.png'),
('Gumball Cookie', 'Bomber', 'Rear', 'Rare', 'gumball-cookie.png'),
('Blackberry Cookie', 'Magic', 'Rear', 'Rare', 'blackberry-cookie.png'),
('Adventurer Cookie', 'Ambush', 'Middle', 'Rare', 'adventurer-cookie.png'),
('Alchemist Cookie', 'Bomber', 'Middle', 'Rare', 'alchemist-cookie.png'),
('Cherry Cookie', 'Bomber', 'Rear', 'Rare', 'cherry-cookie.png'),
('Knight Cookie', 'Defense', 'Front', 'Rare', 'knight-cookie.png'),
('Princess Cookie', 'Charge', 'Front', 'Rare', 'princess-cookie.png'),
('Zoey Cookie', 'Ranged', 'Rear', 'Special', 'zoey-cookie.png'),
('Mira Cookie', 'Charge', 'Front', 'Special', 'mira-cookie.png'),
('Rumi Cookie', 'Ambush', 'Front', 'Special', 'rumi-cookie.png'),
('Marshmallow Bunny Cookie', 'Support', 'Rear', 'Special', 'marshmallow-bunny-cookie.png'),
('Cream Ferret Cookie', 'Support', 'Rear', 'Special', 'cream-ferret-cookie.png'),
('Icicle Yeti Cookie', 'Healing', 'Front', 'Special', 'icicle-yeti-cookie.png'),
('Snapdragon Cookie', 'Support', 'Rear', 'Special', 'snapdragon-cookie.png'),
('Jung Kook Cookie', 'BTS', 'Rear', 'Special', 'jung-kook-cookie.png'),
('V Cookie', 'BTS', 'Rear', 'Special', 'v-cookie.png'),
('Jimin Cookie', 'BTS', 'Rear', 'Special', 'jimin-cookie.png'),
('J-hope Cookie', 'BTS', 'Rear', 'Special', 'j-hope-cookie.png'),
('SUGA Cookie', 'BTS', 'Rear', 'Special', 'suga-cookie.png'),
('Jin Cookie', 'BTS', 'Rear', 'Special', 'jin-cookie.png'),
('RM Cookie', 'BTS', 'Rear', 'Special', 'rm-cookie.png'),
('Tails Cookie', 'Ambush', 'Middle', 'Special', 'tails-cookie.png'),
('Sonic Cookie', 'Ambush', 'Middle', 'Special', 'sonic-cookie.png'),
('Litmus Cookie', 'Healing', 'Rear', 'Epic', 'litmus-cookie.png'),
('Croissant Cookie', 'Support', 'Rear', 'Epic', 'croissant-cookie.png'),
('Ash Salt Cookie', 'Ambush', 'Front', 'Epic', 'ash-salt-cookie.png'),
('Pom-Pom Dough Cookie', 'Support', 'Middle', 'Epic', 'pom-pom-dough-cookie.png'),
('Mold Dough Cookie', 'Charge', 'Front', 'Epic', 'mold-dough-cookie.png'),
('Chess Choco Cookie', 'Bomber', 'Middle', 'Epic', 'chess-choco-cookie.png'),
('Salt Cellar Cookie', 'Defense', 'Front', 'Epic', 'salt-cellar-cookie.png'),
('Charcoal Cookie', 'Magic', 'Rear', 'Epic', 'charcoal-cookie.png'),
('Menthol Cookie', 'Bomber', 'Rear', 'Epic', 'menthol-cookie.png'),
('Seltzer Cookie', 'Support', 'Rear', 'Epic', 'seltzer-cookie.png'),
('Grapefruit Cookie', 'Charge', 'Front', 'Epic', 'grapefruit-cookie.png'),
('Lime Cookie', 'Support', 'Rear', 'Epic', 'lime-cookie.png'),
('Manju Cookie', 'Ambush', 'Rear', 'Epic', 'manju-cookie.png'),
('Jagae Cookie', 'Support', 'Front', 'Epic', 'jagae-cookie.png'),
('Orange Cookie', 'Magic', 'Rear', 'Epic', 'orange-cookie.png'),
('Lemon Cookie', 'Ambush', 'Middle', 'Epic', 'lemon-cookie.png'),
('Cream Soda Cookie', 'Charge', 'Front', 'Epic', 'cream-soda-cookie.png'),
('Sugarfly Cookie', 'Support', 'Rear', 'Epic', 'sugarfly-cookie.png'),
('Pavlova Cookie', 'Ranged', 'Rear', 'Epic', 'pavlova-cookie.png'),
('Agar Agar Cookie', 'Ambush', 'Middle', 'Epic', 'agar-agar-cookie.png'),
('Wedding Cake Cookie', 'Magic', 'Middle', 'Epic', 'wedding-cake-cookie.png'),
('Black Forest Cookie', 'Charge', 'Front', 'Epic', 'black-forest-cookie.png'),
('Black Sapphire Cookie', 'Support', 'Middle', 'Epic', 'black-sapphire-cookie.png'),
('Candy Apple Cookie', 'Bomber', 'Middle', 'Epic', 'candy-apple-cookie.png'),
('Okchun Cookie', 'Healing', 'Middle', 'Epic', 'okchun-cookie.png'),
('Green Tea Mousse Cookie', 'Defense', 'Front', 'Epic', 'green-tea-mousse-cookie.png'),
('Pudding à la Mode Cookie', 'Bomber', 'Rear', 'Epic', 'pudding-a-la-mode-cookie.png'),
('Choco Drizzle Cookie', 'Ambush', 'Middle', 'Epic', 'choco-drizzle-cookie.png'),
('Red Osmanthus Cookie', 'Ranged', 'Middle', 'Epic', 'red-osmanthus-cookie.png'),
('Golden Osmanthus Cookie', 'Bomber', 'Middle', 'Epic', 'golden-osmanthus-cookie.png'),
('Smoked Cheese Cookie', 'Magic', 'Rear', 'Epic', 'smoked-cheese-cookie.png'),
('Nutmeg Tiger Cookie', 'Support', 'Rear', 'Epic', 'nutmeg-tiger-cookie.png'),
('Star Coral Cookie', 'Support', 'Rear', 'Epic', 'star-coral-cookie.png'),
('Peach Blossom Cookie', 'Support', 'Middle', 'Epic', 'peach-blossom-cookie.png'),
('Cloud Haetae Cookie', 'Defense', 'Front', 'Epic', 'cloud-haetae-cookie.png'),
('Street Urchin Cookie', 'Bomber', 'Middle', 'Epic', 'street-urchin-cookie.png'),
('Caramel Choux Cookie', 'Support', 'Rear', 'Epic', 'caramel-choux-cookie.png'),
('Butter Roll Cookie', 'Charge', 'Front', 'Epic', 'butter-roll-cookie.png'),
('Matcha Cookie', 'Magic', 'Middle', 'Epic', 'matcha-cookie.png'),
('Mercurial Knight Cookie', 'Charge', 'Front', 'Epic', 'mercurial-knight-cookie.png'),
('Silverbell Cookie', 'Support', 'Rear', 'Epic', 'silverbell-cookie.png'),
('Rebel Cookie', 'Ambush', 'Front', 'Epic', 'rebel-cookie.png'),
('Crème Brûlée Cookie', 'Ranged', 'Rear', 'Epic', 'creme-brulee-cookie.png'),
('Linzer Cookie', 'Support', 'Rear', 'Epic', 'linzer-cookie.png'),
('Olive Cookie', 'Support', 'Rear', 'Epic', 'olive-cookie.png'),
('Mozzarella Cookie', 'Magic', 'Middle', 'Epic', 'mozzarella-cookie.png'),
('Fettuccine Cookie', 'Defense', 'Front', 'Epic', 'fettuccine-cookie.png'),
('Burnt Cheese Cookie', 'Charge', 'Front', 'Epic', 'burnt-cheese-cookie.png'),
('Frilled Jellyfish Cookie', 'Support', 'Middle', 'Epic', 'frilled-jellyfish-cookie.png'),
('Peppermint Cookie', 'Support', 'Rear', 'Epic', 'peppermint-cookie.png'),
('Black Lemonade Cookie', 'Bomber', 'Middle', 'Epic', 'black-lemonade-cookie.png'),
('Rockstar Cookie', 'Healing', 'Middle', 'Epic', 'rockstar-cookie.png'),
('Tarte Tatin Cookie', 'Ranged', 'Rear', 'Epic', 'tarte-tatin-cookie.png'),
('Royal Margarine Cookie', 'Ambush', 'Middle', 'Epic', 'royal-margarine-cookie.png'),
('Kouign-Amann Cookie', 'Defense', 'Front', 'Epic', 'kouign-amann-cookie.png'),
('Prune Juice Cookie', 'Bomber', 'Middle', 'Epic', 'prune-juice-cookie.png'),
('Space Doughnut', 'Charge', 'Front', 'Epic', 'space-doughnut.png'),
('Blueberry Pie Cookie', 'Magic', 'Middle', 'Epic', 'blueberry-pie-cookie.png'),
('Milky Way Cookie', 'Charge', 'Front', 'Epic', 'milky-way-cookie.png'),
('Prophet Cookie', 'Support', 'Rear', 'Epic', 'prophet-cookie.png'),
('Pinecone Cookie', 'Bomber', 'Front', 'Epic', 'pinecone-cookie.png'),
('Carol Cookie', 'Healing', 'Rear', 'Epic', 'carol-cookie.png'),
('Macaron Cookie', 'Magic', 'Middle', 'Epic', 'macaron-cookie.png'),
('Schwarzwälder', 'Charge', 'Front', 'Epic', 'schwarzwalder.png'),
('Candy Diver Cookie', 'Support', 'Rear', 'Epic', 'candy-diver-cookie.png'),
('Captain Caviar Cookie', 'Bomber', 'Middle', 'Epic', 'captain-caviar-cookie.png'),
('Cream Unicorn Cookie', 'Healing', 'Rear', 'Epic', 'cream-unicorn-cookie.png'),
('Financier Cookie', 'Defense', 'Front', 'Epic', 'financier-cookie.png'),
('Crunchy Chip Cookie', 'Charge', 'Front', 'Epic', 'crunchy-chip-cookie.png'),
('Wildberry Cookie', 'Defense', 'Front', 'Epic', 'wildberry-cookie.png'),
('Cherry Blossom Cookie', 'Ambush', 'Rear', 'Epic', 'cherry-blossom-cookie.png'),
('Caramel Arrow Cookie', 'Ranged', 'Front', 'Epic', 'caramel-arrow-cookie.png'),
('Affogato Cookie', 'Bomber', 'Middle', 'Epic', 'affogato-cookie.png'),
('Tea Knight Cookie', 'Charge', 'Front', 'Epic', 'tea-knight-cookie.png'),
('Eclair Cookie', 'Support', 'Middle', 'Epic', 'eclair-cookie.png'),
('Cocoa Cookie', 'Defense', 'Front', 'Epic', 'cocoa-cookie.png'),
('Cotton Cookie', 'Support', 'Rear', 'Epic', 'cotton-cookie.png'),
('Pumpkin Pie Cookie', 'Magic', 'Middle', 'Epic', 'pumpkin-pie-cookie.png'),
('Twizzly Gummy Cookie', 'Ranged', 'Rear', 'Epic', 'twizzly-gummy-cookie.png'),
('Mala Sauce Cookie', 'Charge', 'Front', 'Epic', 'mala-sauce-cookie.png'),
('Moon Rabbit Cookie', 'Defense', 'Front', 'Epic', 'moon-rabbit-cookie.png'),
('Raspberry Cookie', 'Charge', 'Front', 'Epic', 'raspberry-cookie.png'),
('Parfait Cookie', 'Support', 'Rear', 'Epic', 'parfait-cookie.png'),
('Sorbet Shark Cookie', 'Ambush', 'Middle', 'Epic', 'sorbet-shark-cookie.png'),
('Squid Ink Cookie', 'Magic', 'Middle', 'Epic', 'squid-ink-cookie.png'),
('Lilac Cookie', 'Support', 'Middle', 'Epic', 'lilac-cookie.png'),
('Mango Cookie', 'Magic', 'Middle', 'Epic', 'mango-cookie.png'),
('Red Velvet Cookie', 'Charge', 'Front', 'Epic', 'red-velvet-cookie.png'),
('Pastry Cookie', 'Ranged', 'Rear', 'Epic', 'pastry-cookie.png'),
('Fig Cookie', 'Support', 'Middle', 'Epic', 'fig-cookie.png'),
('Strawberry Crepe Cookie', 'Defense', 'Front', 'Epic', 'strawberry-crepe-cookie.png'),
('Black Raisin Cookie', 'Ambush', 'Middle', 'Epic', 'black-raisin-cookie.png'),
('Almond Cookie', 'Support', 'Middle', 'Epic', 'almond-cookie.png'),
('Cream Puff Cookie', 'Support', 'Middle', 'Epic', 'cream-puff-cookie.png'),
('Latte Cookie', 'Magic', 'Middle', 'Epic', 'latte-cookie.png'),
('Kumiho Cookie', 'Charge', 'Front', 'Epic', 'kumiho-cookie.png'),
('Rye Cookie', 'Ranged', 'Rear', 'Epic', 'rye-cookie.png'),
('Espresso Cookie', 'Magic', 'Middle', 'Epic', 'espresso-cookie.png'),
('Madeleine Cookie', 'Defense', 'Front', 'Epic', 'madeleine-cookie.png'),
('Licorice Cookie', 'Magic', 'Middle', 'Epic', 'licorice-cookie.png'),
('Poison Mushroom Cookie', 'Bomber', 'Middle', 'Epic', 'poison-mushroom-cookie.png'),
('Milk Cookie', 'Defense', 'Front', 'Epic', 'milk-cookie.png'),
('Purple Yam Cookie', 'Charge', 'Front', 'Epic', 'purple-yam-cookie.png'),
('Pomegranate Cookie', 'Support', 'Middle', 'Epic', 'pomegranate-cookie.png'),
('Chili Pepper Cookie', 'Ambush', 'Middle', 'Epic', 'chili-pepper-cookie.png'),
('Sparkling Cookie', 'Healing', 'Rear', 'Epic', 'sparkling-cookie.png'),
('Dark Choco Cookie', 'Charge', 'Front', 'Epic', 'dark-choco-cookie.png'),
('Herb Cookie', 'Healing', 'Rear', 'Epic', 'herb-cookie.png'),
('Mint Choco Cookie', 'Support', 'Rear', 'Epic', 'mint-choco-cookie.png'),
('Werewolf Cookie', 'Charge', 'Front', 'Epic', 'werewolf-cookie.png'),
('Tiger Lily Cookie', 'Ranged', 'Rear', 'Epic', 'tiger-lily-cookie.png'),
('Vampire Cookie', 'Ambush', 'Rear', 'Epic', 'vampire-cookie.png'),
('Snow Sugar Cookie', 'Magic', 'Middle', 'Epic', 'snow-sugar-cookie.png'),
('Povidone-Iodine Cookie', 'Bomber', 'Middle', 'Super Epic', 'povidone-iodine-cookie.png'),
('Venom Dough Cookie', 'Bomber', 'Rear', 'Super Epic', 'venom-dough-cookie.png'),
('Doughael', 'Healing', 'Middle', 'Super Epic', 'doughael.png'),
('Camellia Cookie', 'Charge', 'Front', 'Super Epic', 'camellia-cookie.png'),
('Elder Faerie Cookie', 'Defense', 'Front', 'Super Epic', 'elder-faerie-cookie.png'),
('Crimson Coral Cookie', 'Defense', 'Front', 'Super Epic', 'crimson-coral-cookie.png'),
('Shining Glitter Cookie', 'Magic', 'Middle', 'Super Epic', 'shining-glitter-cookie.png'),
('Capsaicin Cookie', 'Charge', 'Front', 'Super Epic', 'capsaicin-cookie.png'),
('Stardust Cookie', 'Ambush', 'Middle', 'Super Epic', 'stardust-cookie.png'),
('Sherbet Cookie', 'Ranged', 'Middle', 'Super Epic', 'sherbet-cookie.png'),
('Oyster Cookie', 'Support', 'Rear', 'Super Epic', 'oyster-cookie.png'),
('Clotted Cream Cookie', 'Magic', 'Middle', 'Super Epic', 'clotted-cream-cookie.png'),
('Ananas Dragon Cookie', 'Magic', 'Middle', 'Dragon', 'ananas-dragon-cookie.png'),
('Pitaya Dragon Cookie', 'Charge', 'Front', 'Dragon', 'pitaya-dragon-cookie.png'),
('Timekeeper Cookie', 'Magic', 'Middle', 'Legendary', 'timekeeper-cookie.png'),
('Sugar Swan Cookie', 'Healing', 'Rear', 'Legendary', 'sugar-swan-cookie.png'),
('Millennial Tree Cookie', 'Healing', 'Front', 'Legendary', 'millennial-tree-cookie.png'),
('Fire Spirit Cookie', 'Magic', 'Rear', 'Legendary', 'fire-spirit-cookie.png'),
('Wind Archer Cookie', 'Ranged', 'Rear', 'Legendary', 'wind-archer-cookie.png'),
('Stormbringer Cookie', 'Charge', 'Front', 'Legendary', 'stormbringer-cookie.png'),
('Moonlight Cookie', 'Magic', 'Middle', 'Legendary', 'moonlight-cookie.png'),
('Black Pearl Cookie', 'Ambush', 'Middle', 'Legendary', 'black-pearl-cookie.png'),
('Frost Queen Cookie', 'Magic', 'Middle', 'Legendary', 'frost-queen-cookie.png'),
('Sea Fairy Cookie', 'Bomber', 'Middle', 'Legendary', 'sea-fairy-cookie.png'),
('Pure Vanilla Cookie', 'Healing', 'Rear', 'Ancient', 'pure-vanilla-cookie.png'),
('Hollyberry Cookie', 'Defense', 'Front', 'Ancient', 'hollyberry-cookie.png'),
('Dark Cacao Cookie', 'Charge', 'Front', 'Ancient', 'dark-cacao-cookie.png'),
('Golden Cheese Cookie', 'Ranged', 'Middle', 'Ancient', 'golden-cheese-cookie.png'),
('White Lily Cookie', 'Bomber', 'Middle', 'Ancient', 'white-lily-cookie.png'),
('Dark Cacao Cookie (Dragon Lord)', 'Charge', 'Front', 'Ancient', 'dark-cacao-cookie-dragon-lord.png'),
('Golden Cheese Cookie (Immortal)', 'Ranged', 'Middle', 'Ancient', 'golden-cheese-cookie-immortal.png'),
('Pure Vanilla Cookie (Compassionate)', 'Healing', 'Rear', 'Ancient', 'pure-vanilla-cookie-compassionate.png'),
('Hollyberry Cookie (Aegis)', 'Defense', 'Front', 'Ancient', 'hollyberry-cookie-aegis.png'),
('White Lily Cookie (Dawnbringer)', 'Bomber', 'Middle', 'Ancient', 'white-lily-cookie-dawnbringer.png'),
('Mystic Flour Cookie', 'Healing', 'Rear', 'Beast', 'mystic-flour-cookie.png'),
('Burning Spice Cookie', 'Charge', 'Front', 'Beast', 'burning-spice-cookie.png'),
('Shadow Milk Cookie', 'Magic', 'Middle', 'Beast', 'shadow-milk-cookie.png'),
('Eternal Sugar Cookie', 'Bomber', 'Middle', 'Beast', 'eternal-sugar-cookie.png'),
('Silent Salt Cookie', 'Ambush', 'Front', 'Beast', 'silent-salt-cookie.png'),
('Dark Enchantress Cookie', 'Magic', 'Middle', 'Witch', 'dark-enchantress-cookie.png');
